[package]
name = "esp_idf"
version = "0.1.0"
authors = ["Maxim <maxim_dmytrenko@comcast.com>"]
edition = "2021"
resolver = "2"
rust-version = "1.82"

[[bin]]
name = "esp_idf"
harness = false # do not use the built-in cargo test harness -> resolve rust-analyzer errors

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice, and they don't increase the size on Flash
opt-level = "z"
[patch.crates-io]
esp-idf-sys = { git = "https://github.com/esp-rs/esp-idf.git" }
esp-idf-hal = { git = "https://github.com/esp-rs/esp-idf.git" }
esp-idf-svc = { git = "https://github.com/esp-rs/esp-idf.git" }

[package.metadata.esp-idf-sys]
[[package.metadata.esp-idf-sys.extra_components]]
remote_component = { name = "joltwallet/littlefs", version = "1.20.2" }
[[package.metadata.esp-idf-sys.extra_components]]
remote_component = { name = "espressif/mdns", version = "1.8.2" }

[dependencies]
anyhow = "1"
log = "0.4"
esp-idf-svc = { version = "0.53", features = ["critical-section", "embassy-time-driver", "embassy-sync"] }
# Remove `generic-queue-8` if you plan to use `embassy-time` WITH `embassy-executor`
embassy-time = { version = "0.5", features = ["generic-queue-8"] }
heapless = "0.9.3"

[build-dependencies]
embuild = "0.33.5"
